# Production Profile Configuration
spring:
  # Database Configuration for Production
  datasource:
    url: ${DB_URL:jdbc:postgresql://db-prod.nnipa.cloud:5432/tenant_db}
    username: ${DB_USERNAME:tenant_user}
    password: ${DB_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 20000

  # JPA Production Settings
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false

  # Production Cache Settings
  cache:
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=10m

# Server Configuration for Production
server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never
    include-message: always
  compression:
    enabled: true
    min-response-size: 1024

# Logging for Production
logging:
  level:
    root: WARN
    com.nnipa.tenant: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
  file:
    name: ${LOG_PATH:/var/log/nnipa}/tenant-service.log
    max-size: 100MB
    max-history: 90

# Production-specific Application Properties
app:
  tenant:
    development-mode: false
    mock-external-services: false
    security:
      enable-rate-limiting: true
      max-requests-per-minute: 100

# Actuator - Limited endpoints in production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: true